### PR TITLE
new syntax: string macro `latex"\sin^2 x"display`

### PR DESCRIPTION
**Pull request by hhaensel**
This PR addresses #10 and introduces a new syntax. `latex()` generates a `span` rather than a `div`.
The string macro `latex"\sin^2x"mode` accepts raw strings for the latex expression and a mode modifier.
If the expression starts with `:`, the expression is interpreted as a javascript expression, in order to link the entry to a field.

```julia
using Stipple
using StippleUI
using Stipple.ReactiveTools
using StippleLatex

@app begin
    @in text = raw"\sin^2 x"
end

function ui()
    cell(class = "st-module q-ma-md q-pa-md", [
        textfield("LaTeX", :text)
        cell(class = "q-pa-md", latex":text"display)
        cell(class = "q-pa-md", latex"\cos^2x"auto)
        latex(class = "q-pa-md", raw"\tan^2x", display = true) 
    ])
end

route("/") do
    model = @init
    page(model, ui()) |> html
end
    
up()
```

### CODE REVIEW

**Comment by hhaensel** [comment]
Just added `@latex` as promised, so now you can write `cell(@latex(raw"\tanh^2 y", display = true)`. But you can even supply Symbol arguments which are then passed as js expressions.
Have a look at the following app and wait 5s after loading.

```julia
using Stipple, Stipple.ReactiveTools
using StippleUI
using StippleLatex

@app begin
    @in x = 0.00
    @in text = raw"\sin^2 x"
    @private p = @task 1+1
    @onchange isready begin
        if !istaskstarted(p) || istaskdone(p) 
            p = @task begin
                println("Task started")
                while x <= 100
                    x = x + 1
                    sleep(1)
                end
            end
            schedule(p)
        end
    end
end

function ui()
    cell(class = "st-module q-ma-md q-pa-md", [
        bignumber("Counter", :x, color = R"x >= 5 ? 'negative' : 'positive'", icon = "mail")
        textfield("LaTeX", :text)
        cell(class = "q-pa-md", latex":text"display)
        cell(class = "q-pa-md", latex"\cos^2x"auto)
        latex(class = "q-pa-md", raw"\tan^2x", display = true)
        cell(class = "q-pa-md", @latex(raw"\tanh^2 y", display = R"x >= 5"))
    ])
end

route("/") do
    global model
    model = @init
    page(model, ui()) |> html
end
    
up()
```

**Comment by AbhimanyuAryan** [comment]
looks great @hhaensel should merge

**Comment by hhaensel** [comment]
Well, I don't have the rights to do so.
@essenciary should probably take action...

**Comment by PGimenez** [comment]
thanks a lot for the quick update @hhaensel, it works great! I'll do the merge

**Comment by essenciary** [comment]
@hhaensel I've invited you to the repo

**Pull request merged**
